BAL-IK.UI/Areas/SirketYoneticisi/Controllers/PersonellerController.cs
using BAL_IK.Data.Interfaceler.SirketYoneticisi;
using BAL_IK.UI.Filters;
using BAL_IK.UI.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using static BAL_IK.Model.RequestClass.SirketYoneticisiIslemleriRequest;
using static BAL_IK.Model.ResponseClass.PersonelIslemleriResponse;
using static BAL_IK.Model.RequestClass.PersonelIslemleriRequest;
using BAL_IK.Model.Entities;

namespace BAL_IK.UI.Areas.SirketYoneticisi.Controllers
{
    [SirketYoneticisi]
    [Area("SirketYoneticisi")]
    public class PersonellerController : Controller
    {
        private readonly ISirketYoneticisiServis _syServis;

        public PersonellerController(ISirketYoneticisiServis _syServis)
        {
            this._syServis = _syServis;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult HarcamalarYonetim()
        {
            var sirketYoneticisiGuid = HttpContext.Session.GetString("sirketYoneticisi");
            var response = _syServis.HarcamalariGetir(sirketYoneticisiGuid);
            return View(response);
        }
        public IActionResult BelgeGoruntule(string belge)
        {
            ViewBag.belge = belge;
            return View();
        }

        public IActionResult ZimmetYonetim()
        {
            var sirketYoneticisiGuid = HttpContext.Session.GetString("sirketYoneticisi");

            ZimmetSirketYoneticisiViewModel wmZimmet =new ZimmetSirketYoneticisiViewModel();
            wmZimmet.Personeller = _syServis.PersonelleriGetir(sirketYoneticisiGuid).Personeller;
            wmZimmet.ZimmetTurleri=_syServis.ZimmetTurleriniGetir().ZimmetTurleri;

            wmZimmet.Zimmetler = _syServis.ZimmetleriGetir(sirketYoneticisiGuid).Zimmetler;

            return View(wmZimmet);
        }
        [HttpPost]
        public IActionResult ZimmetYonetim(ZimmetSirketYoneticisiViewModel wmZimmet)
        {
            ZimmetEkleRequest req = new ZimmetEkleRequest();
            req.PersonelId = wmZimmet.PersonelId;
            req.ZimmetTuruId = wmZimmet.ZimmetTurId;
            var response = _syServis.ZimmetEkle(req);
            return RedirectToAction("ZimmetYonetim");
        }
        public IActionResult CalisanEkle()
        {

            return View();
        }
        [HttpPost]
        public IActionResult CalisanEkle(PersonelEkle req)
        {
            Personeller pers = new Personeller();
            pers.Ad = req.Ad;
            pers.Soyad = req.Soyad;
            pers.Cinsiyet = req.Cinsiyet;
            pers.DogumTarihi = req.DogumTarihi;
            pers.Eposta = req.Eposta;
            pers.IseBaslama = req.IseBaslama;
            pers.SirketId = req.SirketId;
            pers.TemelMaasBilgisi = req.TemelMaasBilgisi;
            var resp = _syServis.PersonelEklemeIslemi(req);
            return RedirectToAction("CalisanSayfasi");
        }
        public IActionResult CalisanSayfasi()
        {
            //var resp = _syServis.PersonelleriGetir();

            return View();
        }
        public IActionResult CalisanGuncelle(string guid)
        {
            var resp = _syServis.PersGetir(guid);
            PersonelGuncelle pers = new PersonelGuncelle();
            pers.PersonelId = resp.PersonelId;
            pers.Ad = resp.Ad;
            pers.Soyad = resp.Soyad;
            pers.DogumTarihi = resp.DogumTarihi;
            pers.Cinsiyet = resp.Cinsiyet;
            pers.Eposta = resp.Eposta;
            pers.AktifMi = resp.AktifMi;
            pers.TemelMaasBilgisi = resp.TemelMaasBilgisi;
            return View(pers);
        }

        [HttpPost]
        public IActionResult CalisanGuncelle(PersonelGuncelle pers)
        {
            var resp = _syServis.PersonelGuncelleme(pers);
            return RedirectToAction("CalisanSayfasi");
        }
        public IActionResult CalisanSil()
        {
            
            return View();
        }

        [HttpGet]
        public IActionResult CalisanSil(int personelId)
        {
            var resp = _syServis.PersonelSil(personelId);
            return RedirectToAction("CalisanSayfasi");
        }
        public IActionResult OzlukBelgesiEkle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult OzlukBelgesiEkle(OzlukBelgesiEkle req)
        {
            OzlukBelgesi ozluk = new OzlukBelgesi();
            ozluk.OzlukBelgesiAdi = req.OzlukBelgesiAdi;
            ozluk.OzlukBelgesiYolu = req.OzlukBelgesiYolu;
            ozluk.PersonelId = req.PersonelId;
            ozluk.SirketYoneticisiId = req.SirketYoneticisiId;
            ozluk.OlusturulmaZamani = req.OlusturulmaZamani;

            var resp = _syServis.OzlukBelgesiEkle(req);
            return RedirectToAction("OzlukBelgesiSayfasi");
        }
        public IActionResult OzlukBelgesiSayfasi(int ozlukBelgesiId)
        {
            var resp = _syServis.OzlukBelgesiGetir(ozlukBelgesiId);
            return View(resp);
        }
        public IActionResult OzlukBelgesiGuncelleme(int ozlukBelgesiId)
        {
            var resp = _syServis.OzlukBelgesiGetir(ozlukBelgesiId);
            OzlukBelgesiGuncelle ozluk = new OzlukBelgesiGuncelle();
            ozluk.OzlukBelgesiAdi = resp.OzlukBelgesiAdi;
            ozluk.OzlukBelgesiId = resp.OzlukBelgesiId;
            ozluk.OzlukBelgesiYolu = resp.OzlukBelgesiYolu;
            ozluk.OlusturulmaZamani = resp.OlusturulmaZamani;
            ozluk.PersonelId = resp.PersonelId;
            return View(ozluk);
        }
        [HttpPost]
        public IActionResult OzlukBelgesiGuncelleme(OzlukBelgesiGuncelle guncelle)
        {
            var resp = _syServis.OzlukBelgesiGuncelle(guncelle);
            return RedirectToAction("OzlukBelgesiSayfasi");
        }


        public IActionResult VardiyaTur()
        {
            var sirketYoneticisiGuid = HttpContext.Session.GetString("sirketYoneticisi");
            VardiyaTurSirketYoneticisiVM wm = new VardiyaTurSirketYoneticisiVM();
            wm.VardiyaTurRequestVM.SirketYoneticisiGuid = sirketYoneticisiGuid;
            wm.VardiyaTurleri = _syServis.VardiyaTurleriGetir(sirketYoneticisiGuid).VardiyaTurleri;
            return View(wm);
        }
        [HttpPost]
        public IActionResult VardiyaTur(VardiyaTurSirketYoneticisiVM wm)
        {
            var sirketYoneticisiGuid = HttpContext.Session.GetString("sirketYoneticisi");
            wm.VardiyaTurRequestVM.SirketYoneticisiGuid = sirketYoneticisiGuid;
            var response = _syServis.VardiyaTurEkle(wm.VardiyaTurRequestVM);
            wm.VardiyaTurleri = _syServis.VardiyaTurleriGetir(sirketYoneticisiGuid).VardiyaTurleri;
            ViewBag.Sonuc = response.Mesaj;
           return View(wm);
        }
        public IActionResult MolaTur()
        {
            var sirketYoneticisiGuid = HttpContext.Session.GetString("sirketYoneticisi");
            MolaTurSirketYoneticiWM wm = new MolaTurSirketYoneticiWM();
            wm.MolaTurleri = _syServis.MolaTurleriGetir(sirketYoneticisiGuid).MolaTurleri;
            return View(wm);
        }
        [HttpPost]
        public IActionResult MolaTur(MolaTurSirketYoneticiWM wm)
        {
            var sirketYoneticisiGuid = HttpContext.Session.GetString("sirketYoneticisi");
            wm.MolaTur.SirketYoneticisiGuid = sirketYoneticisiGuid;
            var response = _syServis.MolaTurEkle(wm.MolaTur);
            ViewBag.Sonuc = response.Mesaj;
            wm.MolaTurleri = _syServis.MolaTurleriGetir(sirketYoneticisiGuid).MolaTurleri;
            return View(wm);
        }              
        public IActionResult CalisanMolaVardiya()
        {
            var sirketYoneticisiGuid = HttpContext.Session.GetString("sirketYoneticisi");
            CalisaVardiyaEkleWM wm=new CalisaVardiyaEkleWM();
            wm.MolaTurleri = _syServis.MolaTurleriGetir(sirketYoneticisiGuid).MolaTurleri;
            wm.VardiyaTurleri = _syServis.VardiyaTurleriGetir(sirketYoneticisiGuid).VardiyaTurleri;
            wm.Personeller = _syServis.PersonelleriGetir(sirketYoneticisiGuid).Personeller;
            return View(wm);
        }
        [HttpPost]
        public IActionResult CalisanMolaVardiya(CalisaVardiyaEkleWM wm)
        {
            CalisanVardiyaMolaEkleRequest req = new CalisanVardiyaMolaEkleRequest();
            req.VardiyaTurId = wm.VardiyaTurId;
            req.MolaTurIds = wm.MolaTurIds;
            req.PersonelId = wm.PersonelId;
            var response = _syServis.CalisanVardiyaEkle(req);
            ViewBag.Sonuc = response.Mesaj;
            return RedirectToAction("CalisanMolaVardiya");
        }
      

    }
}

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/BelgeGoruntule.cshtml
@{
    Layout = null;
}
<style>

</style>
<img src="~/Uploads/@ViewBag.belge"/>

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/CalisanEkle.cshtml
@using static BAL_IK.Model.ResponseClass.PersonelIslemleriResponse
@using static BAL_IK.Model.RequestClass.PersonelIslemleriRequest
@model PersonelEkleResponse

<table class="table">
    <thead>
        <tr>
            <th scope="col">Personel Adı</th>
            <th scope="col">Personel Soyadı</th>
            <th scope="col">Tutarı</th>
            <th scope="col">Tarihi</th>
            <th scope="col">Belgesi</th>
            <th scope="col">Onay</th>
        </tr>
    </thead>
    @*<tbody>
        @if (Model..Count > 0)
        {
            @foreach (var item in Model.)
            {

                if (harcama.OnayDurumu == true)
                    onay = "checked";

                else
                    onay = "";
                if (harcama.OlusturulmaZamani.Month != DateTime.Now.Month)
                    degisiklik = "disabled";
                else
                    degisiklik = "";



                <tr>
                    <td>@harcama.Personel.Ad</td>
                    <td>@harcama.HarcamaIsmi</td>
                    <td>@harcama.HarcamaTutari</td>
                    <td>@harcama.OlusturulmaZamani.ToShortDateString()</td>
                    <td><a asp-action="BelgeGoruntule" asp-controller="Personeller" asp-route-belge="@harcama.DosyaYolu" target=”_blank”>Belgeyi Görüntüle</a></td>
                    <td>
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="kutu" @degisiklik @onay onchange="onChange(this,@harcama.HarcamaId)">
                            <label class="form-check-label" for="kutu">Harcama Onayı</label>
                        </div>
                    </td>

                </tr>
            }
        }

    </tbody>*@
</table>

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/CalisanGuncelle.cshtml
@using static BAL_IK.Model.RequestClass.PersonelIslemleriRequest

@model PersonelGuncelle

<form method="post">
    <input type="hidden" asp-for="PersonelId" />
    <h6>Ad</h6>
    <input required type="text" asp-for="Ad" />
    <br />
    <h6>Soyad</h6>
    <input required type="text" asp-for="Soyad" />
    <br />
    <h6>Doğum Tarihi</h6>
    <input required type="date" asp-for="DogumTarihi" />
    <br />
    <h6>Cinsiyet</h6>
    <div class="input-group input-group-outline mb-3">
        <select asp-for="Cinsiyet" asp-items="Html.GetEnumSelectList<Cinsiyet>()" class="3col active form-control">
        </select>
    </div>
    
    <h6>E-Posta</h6>
    <input required type="email" asp-for="Eposta" />
    <br />
    <h6>Personel Aktif mi?</h6>
    <input asp-for="AktifMi" />
    @*<input required type="date" asp-for="YillikIzinHakki" />
        <input required type="date" asp-for="IseBaslama" />
        <input required type="date" asp-for="IstenAyrilma" />*@
    <br />
    <h6>Maaş</h6>
    <input required type="number" asp-for="TemelMaasBilgisi" />
    <br />
    <br />



    <button class="btn btn-primary" onclick="confirmAction(@Model.PersonelId)">Güncelle</button>
</form>

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/CalisanMolaVardiya.cshtml
@using BAL_IK.UI.ViewModels
@model CalisaVardiyaEkleWM




<table class="table">
    <thead>
        <tr>
            <th scope="col">Personel Adı</th>
            <th scope="col">Vardiyası</th>
            <th scope="col">Molaları</th>
            <th scope="col">İşlem</th>
        </tr>
    </thead>
    <tbody>

        @foreach (var personel in Model.Personeller.ToList())
        {


            string VardiyaBilgi = @personel.Guid.ToString() + "VardiyaBilgi";

            string VardiyaSec = @personel.Guid.ToString() + "VardiyaSec";

            string MolaBilgi = @personel.Guid.ToString() + "MolaBilgi";

            string MolaSec = @personel.Guid.ToString() + "MolaSec";

            string BtnDuzenle = @personel.Guid.ToString() + "BtnDuzenle";

            string BtnIptal = @personel.Guid.ToString() + "BtnIptal";

            string BtnKaydet = @personel.Guid.ToString() + "BtnKaydet";

            <form method="post">
            <tr>
                <input asp-for="PersonelId" value="@personel.PersonelId" hidden />
                <td>@personel.Ad @personel.Soyad</td>
                <td hidden id="@{
                                @VardiyaSec
}">
                    <select class="form-select mb-2" aria-label="Default select example" asp-for="VardiyaTurId"
                        asp-items="@(new SelectList(Model.VardiyaTurleri,"VardiyaTurId","VardiyaTuru"))">
                        <option>Vardiya Seç</option>
                    </select>
                </td>
                <td id="@{
                                    @VardiyaBilgi
}">

                        @foreach (var vardiyalar in @Model.VardiyaTurleri.Select(x => x.Vardiyalar).ToList())
                        {
                            @foreach (var vardiya in vardiyalar)
                            {

                                if (vardiya.PersonelId == personel.PersonelId)
                                {
                                <p>@Model.VardiyaTurleri.FirstOrDefault(x=>x.VardiyaTurId==vardiya.VardiyaTurId).VardiyaTuru</p>

                                }
                            }
                        }

                </td>
                <td hidden id="@{
                                    @MolaSec
}">
                    <select multiple="" class="form-control pb-4" aria-label="Default select example" asp-for="MolaTurIds"
                        asp-items="@(new SelectList(Model.MolaTurleri,"MolaTurId","MolaTuru"))">
                    </select>
                </td>
                <td id="@{
                                    @MolaBilgi
}">
                        @foreach (var molaTurleri in @Model.MolaTurleri.ToList())
                        {
                            @foreach (var item in molaTurleri.Molalar.Where(x => x.PersonelId == personel.PersonelId).ToList())
                            {
                            <span>@molaTurleri.MolaTuru ,</span>
                            }
                        }
                </td>
                <td>
                    <a class="btn btn-warning" id="@{
                                @BtnDuzenle
}" onclick="Duzenle('@personel.Guid.ToString()')">Düzenle</a>
                    <a hidden class="btn btn-danger" id="@{
                                    @BtnIptal
}" onclick="Iptal('@personel.Guid.ToString()')">İptal</a>
                    <button hidden id="@{
                                        @BtnKaydet
}" class="btn btn-info">
                        Kaydet
                    </button>
                </td>





            </tr>


            </form>


        }


    </tbody>
</table>

<script>
    function Duzenle(guid){
        var VardiyaBilgi=guid+"VardiyaBilgi";
        var VardiyaSec=guid+"VardiyaSec";
        var MolaBilgi=guid+"MolaBilgi";
        var MolaSec=guid+"MolaSec";
        var BtnDuzenle=guid+"BtnDuzenle";
        var BtnIptal=guid+"BtnIptal";
        var BtnKaydet=guid+"BtnKaydet";
        document.getElementById(VardiyaBilgi).hidden=true;
        document.getElementById(VardiyaSec).hidden=false;
        document.getElementById(MolaBilgi).hidden=true;
        document.getElementById(MolaSec).hidden=false;
        document.getElementById(BtnDuzenle).hidden=true;
        document.getElementById(BtnIptal).hidden=false;
        document.getElementById(BtnKaydet).hidden=false;



    }
       function Iptal(guid){
          var VardiyaBilgi=guid+"VardiyaBilgi";
        var VardiyaSec=guid+"VardiyaSec";
        var MolaBilgi=guid+"MolaBilgi";
        var MolaSec=guid+"MolaSec";
        var BtnDuzenle=guid+"BtnDuzenle";
        var BtnIptal=guid+"BtnIptal";
        var BtnKaydet=guid+"BtnKaydet";
        document.getElementById(VardiyaBilgi).hidden=false;
        document.getElementById(VardiyaSec).hidden=true;
        document.getElementById(MolaBilgi).hidden=false;
        document.getElementById(MolaSec).hidden=true;
        document.getElementById(BtnDuzenle).hidden=false;
        document.getElementById(BtnIptal).hidden=true;
        document.getElementById(BtnKaydet).hidden=true;

    }



</script>

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/CalisanSayfasi.cshtml
@using static BAL_IK.Model.ResponseClass.SirketIslemleriResponse
@model PersonelleriGetirResponse

<a class="btn btn-primary" asp-action="CalisanEkle" asp-controller="Personeller" asp-area="SirketYoneticisi">Personel Ekle</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Personel Adı Soyadı</th>
            <th scope="col">E-Posta</th>
            <th scope="col">Cinsiyet</th>
            <th scope="col">Personel Aktif Mi</th>
            <th scope="col">Maaş</th>
            <th scope="col">İşlem</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Personeller.Count > 0)
        {
            @foreach (var personel in Model.Personeller.OrderByDescending(x => x.PersonelId))
            {
                <tr>
                    <input asp-for="@personel.PersonelId" type="hidden" />
                    <td>@personel.Ad @personel.Soyad</td>
                    <td>@personel.Eposta</td>
                    <td>@personel.Cinsiyet</td>
                    <td>@personel.AktifMi</td>
                    <td>@personel.TemelMaasBilgisi</td>
                    <td><a class="btn btn-dark" asp-action="CalisanGuncelle" asp-controller="Personeller" asp-route-guid="@personel.Guid">Güncelle</a><a class="btn btn-danger" onclick="confirmAction(@personel.PersonelId)">Sil</a></td>


                </tr>
            }
        }

    </tbody>
</table>


@section scripts
{

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script>

        $('#myModal').on('shown.bs.modal', function () {
            $('#myInput').trigger('focus')
        });

        function confirmAction(id) {
            let confirmAction = confirm("Personel silinecek. Emin misiniz?");
            if (confirmAction) {
                $.ajax(
                    {
                        url: 'http://localhost:46375/api/SirketYoneticisi/PersonelSil?pers=' + id,
                        method: "POST",
                        success: function (data) {

                        },

                    });
            } else {

            }
            location.reload();
        }

    </script>
}

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/HarcamalarYonetim.cshtml
@using static BAL_IK.Model.ResponseClass.SirketYoneticisiIslemleriResponse
@model HarcamalarResponse
@{
    string onay;
    string degisiklik;
}

<table class="table">
    <thead>
        <tr>           
            <th scope="col">Personel Adı</th>
            <th scope="col">Harcama Adı</th>
            <th scope="col">Tutarı</th>
            <th scope="col">Tarihi</th>
            <th scope="col">Belgesi</th>
            <th scope="col">Onay</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Harcamalar.Count > 0)
        {
            @foreach (var harcama in Model.Harcamalar.OrderByDescending(x=>x.OlusturulmaZamani))
            {

                if (harcama.OnayDurumu == true)
                    onay = "checked";

                else
                    onay = "";
                if (harcama.OlusturulmaZamani.Month != DateTime.Now.Month)
                    degisiklik = "disabled";
                else
                    degisiklik = "";



                <tr>
                    <td>@harcama.Personel.Ad</td>
                    <td>@harcama.HarcamaIsmi</td>
                    <td>@harcama.HarcamaTutari</td>
                    <td>@harcama.OlusturulmaZamani.ToShortDateString()</td>
                    <td><a asp-action="BelgeGoruntule" asp-controller="Personeller" asp-route-belge="@harcama.DosyaYolu" target=”_blank”>Belgeyi Görüntüle</a></td>
                    <td>
                        <div class="form-check form-switch">
                            <input class="form-check-input"  type="checkbox" id="kutu" @degisiklik  @onay onchange="onChange(this,@harcama.HarcamaId)">
                            <label class="form-check-label" for="kutu">Harcama Onayı</label>
                        </div>
                    </td>

                </tr>
            }
        }

    </tbody>
</table>

@section scripts
{
     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
   
        const kutu=document.getElementById("kutu").value;

   function onChange(element,id) {
    	console.log('Agreement changed to ' + element.checked + id);  
        if(element.checked) {
                  $.ajax(
             { 
            url:'http://localhost:46375/api/SirketYoneticisi/HarcamaOnay?id='+id+'&durum=true',
            method:"POST",
            success: function(data)
            {
             console.log(data)

            },
           
             });  
        }  
        else
        {
            $.ajax(
             { 
            url:'http://localhost:46375/api/SirketYoneticisi/HarcamaOnay?id='+id+'&durum=false',
            method:"POST",
            success: function(data)
            {
             console.log(data)

            },
           
             });  
        }
   }

</script>
}

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/OzlukBelgesiEkle.cshtml
@using static BAL_IK.Model.RequestClass.PersonelIslemleriRequest
@model OzlukBelgesiEkle


<form method="post">

    <input type="hidden" asp-for="PersonelId" />
    <input required type="text" asp-for="OzlukBelgesiAdi" />
    <input required type="text" asp-for="OzlukBelgesiYolu" />
    <button class="btn btn-primary" @*onclick="confirmAction(@Model.PersonelId)"asp-action="CalisanGuncelle" asp-controller="Personeller"*@>Personel Ekle</button>
</form>

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/OzlukBelgesiGuncelleme.cshtml
@using static BAL_IK.Model.RequestClass.PersonelIslemleriRequest

@model OzlukBelgesiGuncelle

<form method="post">
    <input type="hidden" asp-for="PersonelId" />
    <input type="hidden" asp-for="OzlukBelgesiId" />
    <h6>Belge Adı</h6>
    <input required type="text" asp-for="OzlukBelgesiAdi" />
    <br />
    <h6>Belge Yolu</h6>
    <input required type="text" asp-for="OzlukBelgesiYolu" />
    <br />
    <h6>E-Posta</h6>
    <input required type="date" asp-for="OlusturulmaZamani" />
    <br />
    <br />
    <button class="btn btn-primary" onclick="confirmAction(@Model.PersonelId)">Güncelle</button>
</form>

BAL-IK.UI/Areas/SirketYoneticisi/Views/Personeller/OzlukBelgesiSayfasi.cshtml
@using static BAL_IK.Model.ResponseClass.PersonelIslemleriResponse
@model OzlukBelgesiGetirResponse

<a class="btn btn-primary" asp-action="OzlukBelgesiEkle" asp-controller="Personeller" asp-area="SirketYoneticisi">Özlük Belgesi Ekle</a>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Özlük Belgesi Adı</th>
            <th scope="col">Belge Yolu</th>
        </tr>
    </thead>
    <tbody>
        @*@if (Model.OzlukBelgeleri.Count > 0)
        {*@
            @*@foreach (var personel in Model.OzlukBelgeleri.OrderByDescending(x => x.PersonelId))
            {
                <tr>
                    <input asp-for="@personel.PersonelId" type="hidden" />
                    <td>@personel.OzlukBelgesiAdi</td>
                    <td>@personel.OzlukBelgesiYolu</td>                    
                    <td><a class="btn btn-secondary" asp-action="OzlukBelgesiGuncelle" asp-controller="Personeller" asp-route-guid="@personel.PersonelId">Güncelle</a><a class="btn btn-warning">Sil</a></td>


                </tr>
            }*@
        

    </tbody>
</table>